[application]

[web.app]

# HTML title tag content
title = "pwa"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.pwa]
enabled = true
manifest = "manifest.json"
service_worker = "sw.js"