/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-30T19:13:45.368864307+00:00
/// Collection: lucide
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/lucide/>
///
/// ```yaml
/// name: Lucide
/// author:
///   name: Lucide Contributors
///   url: https://github.com/lucide-icons/lucide
/// license:
///   title: ISC
///   spdx: ISC
///   url: https://github.com/lucide-icons/lucide/blob/main/LICENSE
/// total: 1744
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const User: IconData = IconData {
    name: "lucide:user",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path vector-effect="non-scaling-stroke" d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle vector-effect="non-scaling-stroke" cx="12" cy="7" r="4"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
