/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-07-22T14:55:02.793707829+00:00
/// Collection: material-symbols-light
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/material-symbols-light/>
///
/// ```yaml
/// name: Material Symbols Light
/// author:
///   name: Google
///   url: https://github.com/google/material-design-icons
/// license:
///   title: Apache 2.0
///   spdx: Apache-2.0
///   url: https://github.com/google/material-design-icons/blob/master/LICENSE
/// total: 15642
/// category: Material
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const AddRounded: IconData = IconData {
    name: "material-symbols-light:add-rounded",
    body: r#"<path fill="currentColor" d="M11.5 12.5h-5q-.213 0-.356-.144T6 11.999t.144-.356t.356-.143h5v-5q0-.213.144-.356T12.001 6t.356.144t.143.356v5h5q.213 0 .356.144t.144.357t-.144.356t-.356.143h-5v5q0 .213-.144.356t-.357.144t-.356-.144t-.143-.356z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const ArchiveOutlineRounded: IconData = IconData {
    name: "material-symbols-light:archive-outline-rounded",
    body: r#"<path fill="currentColor" d="M11.643 10.72q-.143.143-.143.357v4.2l-1.746-1.746q-.14-.14-.344-.15t-.364.15t-.16.354t.16.354l2.389 2.388q.242.242.565.242t.566-.242l2.388-2.388q.14-.141.15-.345t-.15-.363t-.354-.16t-.354.16L12.5 15.277v-4.2q0-.213-.143-.357T12 10.577t-.357.143M5 7.808v10.577q0 .269.173.442t.443.173h12.769q.269 0 .442-.173t.173-.442V7.808zM5.77 20q-.672 0-1.221-.549T4 18.231V7.486q0-.292.093-.55t.28-.475l1.558-1.87q.217-.293.543-.442T7.173 4h9.616q.372 0 .708.149t.553.441l1.577 1.91q.187.217.28.485q.093.267.093.56V18.23q0 .671-.549 1.22t-1.22.549zM5.38 6.808H18.6L17.27 5.21q-.097-.096-.222-.153T16.788 5H7.192q-.134 0-.26.058t-.22.154zM12 13.404"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const ArrowBackIosRounded: IconData = IconData {
    name: "material-symbols-light:arrow-back-ios-rounded",
    body: r#"<path fill="currentColor" d="m2.82 12l7.715 7.716q.22.22.218.528t-.224.529t-.529.221t-.529-.221L1.83 13.137q-.242-.243-.354-.54q-.111-.299-.111-.597t.111-.596q.112-.298.354-.54L9.47 3.22q.221-.221.532-.218q.31.003.532.224q.22.221.22.529t-.22.529z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const ArrowForwardIosRounded: IconData = IconData {
    name: "material-symbols-light:arrow-forward-ios-rounded",
    body: r#"<path fill="currentColor" d="M15.187 12L7.47 4.285q-.221-.221-.218-.532q.003-.31.224-.532Q7.698 3 8.009 3q.31 0 .532.221l7.636 7.643q.242.242.354.54t.111.596t-.111.596t-.354.54L8.535 20.78q-.222.221-.53.218q-.307-.003-.528-.224t-.221-.532t.221-.531z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Book4OutlineRounded: IconData = IconData {
    name: "material-symbols-light:book-4-outline-rounded",
    body: r#"<path fill="currentColor" d="M6.23 21q-.929 0-1.58-.65Q4 19.698 4 18.77V5.23q0-.929.65-1.58Q5.302 3 6.23 3H15q.666 0 1.14.475q.476.474.476 1.14V16q0 .666-.475 1.14q-.475.476-1.141.476H6.23q-.501 0-.865.341Q5 18.3 5 18.804t.365.85t.866.346h12.154q.269 0 .442-.173t.173-.442V5.5q0-.213.144-.356T19.501 5t.356.144T20 5.5v13.885q0 .666-.475 1.14t-1.14.475zm2.155-4.384H15q.27 0 .442-.174q.173-.173.173-.442V4.616q0-.27-.173-.443T15 4H8.385zm-1 0V4H6.23q-.523 0-.877.365Q5 4.728 5 5.23v11.79q.27-.171.574-.288t.657-.117zM5 4v13.021z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const CloseRounded: IconData = IconData {
    name: "material-symbols-light:close-rounded",
    body: r#"<path fill="currentColor" d="m12 12.708l-5.246 5.246q-.14.14-.344.15t-.364-.15t-.16-.354t.16-.354L11.292 12L6.046 6.754q-.14-.14-.15-.344t.15-.364t.354-.16t.354.16L12 11.292l5.246-5.246q.14-.14.345-.15q.203-.01.363.15t.16.354t-.16.354L12.708 12l5.246 5.246q.14.14.15.345q.01.203-.15.363t-.354.16t-.354-.16z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const DeleteOutlineRounded: IconData = IconData {
    name: "material-symbols-light:delete-outline-rounded",
    body: r#"<path fill="currentColor" d="M7.616 20q-.667 0-1.141-.475T6 18.386V6h-.5q-.213 0-.356-.144T5 5.499t.144-.356T5.5 5H9q0-.31.23-.54t.54-.23h4.46q.31 0 .54.23T15 5h3.5q.213 0 .356.144t.144.357t-.144.356T18.5 6H18v12.385q0 .666-.475 1.14t-1.14.475zM17 6H7v12.385q0 .269.173.442t.443.173h8.769q.269 0 .442-.173t.173-.442zm-6.335 10.856q.143-.144.143-.356v-8q0-.213-.144-.356T10.307 8t-.356.144t-.143.356v8q0 .213.144.356q.144.144.356.144q.213 0 .357-.144m3.384 0q.143-.144.143-.356v-8q0-.213-.144-.356Q13.904 8 13.692 8q-.213 0-.357.144t-.143.356v8q0 .213.144.356t.357.144t.356-.144M7 6v13z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const HomeOutlineRounded: IconData = IconData {
    name: "material-symbols-light:home-outline-rounded",
    body: r#"<path fill="currentColor" d="M6 19h3.692v-5.077q0-.343.233-.575q.232-.233.575-.233h3q.343 0 .576.233q.232.232.232.575V19H18v-8.692q0-.154-.067-.28t-.183-.22L12.366 5.75q-.154-.134-.366-.134t-.365.134L6.25 9.808q-.115.096-.183.22t-.067.28zm-1 0v-8.692q0-.384.172-.727t.474-.565l5.385-4.078q.423-.323.966-.323t.972.323l5.385 4.077q.303.222.474.566q.172.343.172.727V19q0 .402-.299.701T18 20h-3.884q-.344 0-.576-.232q-.232-.233-.232-.576v-5.076h-2.616v5.076q0 .344-.232.576T9.885 20H6q-.402 0-.701-.299T5 19m7-6.711"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const MenuRounded: IconData = IconData {
    name: "material-symbols-light:menu-rounded",
    body: r#"<path fill="currentColor" d="M4.5 17.27q-.213 0-.356-.145T4 16.768t.144-.356t.356-.143h15q.213 0 .356.144q.144.144.144.357t-.144.356t-.356.143zm0-4.77q-.213 0-.356-.144T4 11.999t.144-.356t.356-.143h15q.213 0 .356.144t.144.357t-.144.356t-.356.143zm0-4.77q-.213 0-.356-.143Q4 7.443 4 7.23t.144-.356t.356-.143h15q.213 0 .356.144T20 7.23t-.144.356t-.356.144z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const NotificationsOutlineRounded: IconData = IconData {
    name: "material-symbols-light:notifications-outline-rounded",
    body: r#"<path fill="currentColor" d="M5.5 18.77q-.213 0-.356-.145T5 18.268t.144-.356t.356-.143h1.116V9.846q0-1.96 1.24-3.447T11 4.546V4q0-.417.291-.708q.291-.292.707-.292t.709.292T13 4v.546q1.904.365 3.144 1.853t1.24 3.447v7.923H18.5q.213 0 .356.144q.144.144.144.357t-.144.356t-.356.143zm6.497 2.615q-.668 0-1.14-.475t-.472-1.14h3.23q0 .67-.475 1.142q-.476.472-1.143.472M7.616 17.77h8.769V9.846q0-1.823-1.281-3.104T12 5.462t-3.104 1.28t-1.28 3.104z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const PersonOutlineRounded: IconData = IconData {
    name: "material-symbols-light:person-outline-rounded",
    body: r#"<path fill="currentColor" d="M9.877 10.508Q9 9.63 9 8.385t.877-2.123T12 5.385t2.123.877T15 8.385t-.877 2.123t-2.123.877t-2.123-.877M5 17.577v-.608q0-.619.36-1.158q.361-.54.97-.838q1.416-.679 2.834-1.018q1.417-.34 2.836-.34t2.837.34t2.832 1.018q.61.298.97.838q.361.539.361 1.158v.608q0 .44-.299.74q-.299.298-.74.298H6.04q-.441 0-.74-.299t-.3-.739m1 .039h12v-.647q0-.332-.215-.625q-.214-.292-.593-.494q-1.234-.598-2.542-.916T12 14.616t-2.65.318t-2.542.916q-.38.202-.593.494Q6 16.637 6 16.97zm7.413-7.819Q14 9.21 14 8.385t-.587-1.413T12 6.385t-1.412.587T10 8.385t.588 1.412t1.412.588t1.413-.588M12 17.616"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const SettingsOutlineRounded: IconData = IconData {
    name: "material-symbols-light:settings-outline-rounded",
    body: r#"<path fill="currentColor" d="M10.96 21q-.349 0-.605-.229q-.257-.229-.319-.571l-.263-2.092q-.479-.145-1.036-.454q-.556-.31-.947-.664l-1.915.824q-.317.14-.644.03t-.504-.415L3.648 15.57q-.177-.305-.104-.638t.348-.546l1.672-1.25q-.045-.272-.073-.559q-.03-.288-.03-.559q0-.252.03-.53q.028-.278.073-.626l-1.672-1.25q-.275-.213-.338-.555t.113-.648l1.06-1.8q.177-.287.504-.406t.644.021l1.896.804q.448-.373.97-.673q.52-.3 1.013-.464l.283-2.092q.061-.342.318-.571T10.96 3h2.08q.349 0 .605.229q.257.229.319.571l.263 2.112q.575.202 1.016.463t.909.654l1.992-.804q.318-.14.645-.021t.503.406l1.06 1.819q.177.306.104.638t-.348.547L18.36 10.92q.082.31.092.569t.01.51q0 .233-.02.491q-.019.259-.088.626l1.69 1.27q.275.213.358.546t-.094.638l-1.066 1.839q-.176.306-.513.415q-.337.11-.654-.03l-1.923-.824q-.467.393-.94.673t-.985.445l-.264 2.111q-.061.342-.318.571t-.605.23zm.04-1h1.956l.369-2.708q.756-.2 1.36-.549q.606-.349 1.232-.956l2.495 1.063l.994-1.7l-2.189-1.644q.125-.427.166-.786q.04-.358.04-.72q0-.38-.04-.72t-.166-.747l2.227-1.683l-.994-1.7l-2.552 1.07q-.454-.499-1.193-.935q-.74-.435-1.4-.577L13 4h-1.994l-.312 2.689q-.756.161-1.39.52q-.633.358-1.26.985L5.55 7.15l-.994 1.7l2.169 1.62q-.125.336-.175.73t-.05.82q0 .38.05.755t.156.73l-2.15 1.645l.994 1.7l2.475-1.05q.589.594 1.222.953q.634.359 1.428.559zm.973-5.5q1.046 0 1.773-.727T14.473 12t-.727-1.773t-1.773-.727q-1.052 0-1.776.727T9.473 12t.724 1.773t1.776.727M12 12"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const SwapHorizRounded: IconData = IconData {
    name: "material-symbols-light:swap-horiz-rounded",
    body: r#"<path fill="currentColor" d="m4.921 15.173l2.74 2.74q.141.14.15.342q.01.2-.15.366q-.165.165-.356.165t-.357-.165l-3.383-3.383q-.13-.13-.183-.267t-.053-.298t.053-.298t.184-.267l3.388-3.389q.146-.146.344-.153t.364.159q.16.165.162.354t-.162.354l-2.74 2.74h6.886q.213 0 .357.143t.143.357t-.143.357t-.357.143zM19.08 9.808h-6.887q-.213 0-.356-.144t-.144-.356t.144-.357t.356-.143h6.887l-2.74-2.74q-.141-.141-.15-.342t.15-.366q.165-.166.356-.166q.192 0 .357.166l3.383 3.382q.13.131.183.267q.053.137.053.299t-.053.298q-.052.136-.183.267l-3.389 3.389q-.146.146-.344.153q-.198.006-.363-.16q-.16-.164-.163-.353t.163-.354z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const UserAttributesOutlineRounded: IconData = IconData {
    name: "material-symbols-light:user-attributes-outline-rounded",
    body: r#"<path fill="currentColor" d="M14.866 6.73q-.213 0-.357-.143q-.143-.144-.143-.357t.143-.356t.357-.143h6q.212 0 .356.144t.143.357t-.143.356t-.357.143zm0 3.77q-.213 0-.357-.144t-.143-.357t.143-.356t.357-.143h6q.212 0 .356.144t.143.357t-.143.356t-.357.143zm0 3.77q-.213 0-.357-.145t-.143-.357t.143-.356t.357-.143h6q.212 0 .356.144q.143.144.143.357t-.143.356t-.357.143zm-8.577-1.304q-.654-.65-.654-1.577q0-.928.649-1.581q.65-.654 1.577-.654q.928 0 1.581.65q.654.648.654 1.576t-.65 1.581q-.648.654-1.576.654t-1.581-.649m-3.654 5.073v-.324q0-.326.163-.622t.44-.474q1.049-.598 2.196-.916t2.432-.319t2.431.319q1.147.318 2.195.916q.277.179.44.474t.164.622v.323q0 .344-.232.576t-.575.232H3.442q-.343 0-.575-.232t-.233-.576m1.035-.5v.308h8.393v-.308q-.99-.557-2.052-.855q-1.062-.299-2.144-.299t-2.145.299q-1.061.298-2.052.855m5.063-5.287q.364-.365.364-.867q0-.501-.364-.866t-.866-.364t-.867.364t-.364.866t.364.867t.867.364q.501 0 .866-.364m-.866 5.595"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const WarningOutlineRounded: IconData = IconData {
    name: "material-symbols-light:warning-outline-rounded",
    body: r#"<path fill="currentColor" d="M4.126 20q-.234 0-.414-.111t-.28-.293q-.108-.179-.12-.387q-.01-.209.118-.421L11.3 5.212q.128-.212.308-.308T12 4.808t.391.096t.308.308l7.871 13.576q.128.212.115.417t-.118.391t-.282.295t-.41.109zm.324-1h15.1L12 6zm7.984-1.566q.182-.182.182-.434t-.182-.434t-.434-.181t-.434.181t-.182.434t.182.434t.434.181t.434-.181m-.077-2.193q.143-.144.143-.356v-4q0-.213-.144-.357t-.357-.143t-.356.143t-.143.357v4q0 .212.144.356t.357.144t.356-.144M12 12.5"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
