/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-07-07T19:37:52.312591690+00:00
/// Collection: mdi-light
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/mdi-light/>
///
/// ```yaml
/// name: Material Design Light
/// author:
///   name: Pictogrammers
///   url: https://github.com/Templarian/MaterialDesignLight
/// license:
///   title: Open Font License
///   spdx: OFL-1.1
///   url: https://github.com/Templarian/MaterialDesignLight/blob/master/LICENSE.md
/// total: 284
/// category: Material
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Pencil: IconData = IconData {
    name: "mdi-light:pencil",
    body: r#"<path fill="currentColor" d="m19.71 8.04l-2.34 2.33l-3.75-3.75l2.34-2.33c.39-.39 1.04-.39 1.41 0l2.34 2.34c.39.37.39 1.02 0 1.41M3 17.25L13.06 7.18l3.75 3.75L6.75 21H3zM16.62 5.04l-1.54 1.54l2.34 2.34l1.54-1.54zM15.36 11L13 8.64l-9 9.02V20h2.34z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Pin: IconData = IconData {
    name: "mdi-light:pin",
    body: r#"<path fill="currentColor" d="M14 12.41V5h1V4H8v1h1v7.41l-2 2V15h9v-.59zM17 14v2h-5v4.5l-.5 1.5l-.5-1.5V16H6v-2l2-2V6H7V3h9v3h-1v6z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
